/* Copyright (C) 2007 - 2011 YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

jQuery(function(a){window.submitbutton=function(a){if(a=="cancel")window.location="index.php?option=com_widgetkit"};window.Joomla=window.Joomla||{};window.Joomla.submitbutton=window.submitbutton;a("#tabs").tabs();a("#widgetkit").delegate(".box .deletable","click",function(){a(this).parent().trigger("delete",[a(this)])});a("input:text").placeholder();a(".actions .save").css("display","none").length&&(a("#toolbar tr").prepend('<td id="toolbar-apply"><a href="#"><span class="icon-32-apply"></span>Apply</a></td>'),
a("#toolbar ul").prepend('<li id="toolbar-apply"><a href="#"><span class="icon-32-apply"></span>Save</a></li>'),a("#toolbar-apply").bind("click",function(){a("#toolbar").addClass("saving");a(".actions .save").trigger("click")}),a(".actions .save").bind("complete",function(){a("#toolbar").removeClass("saving")}))});
(function(a){a.fn.tabs=function(){return this.each(function(){var c=a(this).addClass("content").wrap('<div class="tabs-box" />').before('<ul class="nav" />'),b=a(this).prev("ul.nav");c.children("li").each(function(){b.append("<li><a>"+a(this).hide().attr("data-name")+"</a></li>")});b.children("li").bind("click",function(d){d.preventDefault();var d=a("li",b).removeClass("active").index(a(this).addClass("active")),f=c.children("li").hide();a(f[d]).show();a.cookie("widgetkit-tab",d,{path:"/"})});var f=
parseInt(a.cookie("widgetkit-tab"));a(!isNaN(f)?b.children("li").get(f):b.children("li:first")).trigger("click")})}})(jQuery);
(function(a){var c=function(){};a.extend(c.prototype,{name:"finder",initialize:function(b,c){function d(c){c.preventDefault();var e=a(this).closest("li",b);e.length||(e=b);e.hasClass(g.options.open)?e.removeClass(g.options.open).children("ul").slideUp():(e.addClass(g.options.loading),a.post(g.options.url,{path:e.data("path")},function(b){e.removeClass(g.options.loading).addClass(g.options.open);b.length&&(e.children().remove("ul"),e.append("<ul>").children("ul").hide(),a.each(b,function(b,c){e.children("ul").append(a('<li><a href="#">'+
c.name+"</a></li>").addClass(c.type).data("path",c.path))}),e.find("ul a").bind("click",d),e.children("ul").slideDown())},"json"))}var g=this;this.options=a.extend({url:"",path:"",open:"open",loading:"loading"},c);b.data("path",this.options.path).bind("retrieve:finder",d).trigger("retrieve:finder")}});a.fn[c.prototype.name]=function(){var b=arguments,f=b[0]?b[0]:null;return this.each(function(){var d=a(this);if(c.prototype[f]&&d.data(c.prototype.name)&&f!="initialize")d.data(c.prototype.name)[f].apply(d.data(c.prototype.name),
Array.prototype.slice.call(b,1));else if(!f||a.isPlainObject(f)){var g=new c;c.prototype.initialize&&g.initialize.apply(g,a.merge([d],b));d.data(c.prototype.name,g)}else a.error("Method "+f+" does not exist on jQuery."+c.name)})}})(jQuery);
(function(a){function c(b){var c={},d=/^jQuery\d+$/;a.each(b.attributes,function(a,b){if(b.specified&&!d.test(b.name))c[b.name]=b.value});return c}function b(){var b=a(this);b.val()===b.attr("placeholder")&&b.hasClass("placeholder")&&(b.data("placeholder-password")?b.hide().next().show().focus():b.val("").removeClass("placeholder"))}function f(){var d,e=a(this);if(e.val()===""||e.val()===e.attr("placeholder")){if(e.is(":password")){if(!e.data("placeholder-textinput")){try{d=e.clone().attr({type:"text"})}catch(f){d=
a("<input>").attr(a.extend(c(e[0]),{type:"text"}))}d.removeAttr("name").data("placeholder-password",!0).bind("focus.placeholder",b);e.data("placeholder-textinput",d).before(d)}e=e.hide().prev().show()}e.addClass("placeholder").val(e.attr("placeholder"))}else e.removeClass("placeholder")}var d="placeholder"in document.createElement("input"),g="placeholder"in document.createElement("textarea");a.fn.placeholder=d&&g?function(){return this}:function(){return this.filter((d?"textarea":":input")+"[placeholder]").bind("focus.placeholder",
b).bind("blur.placeholder",f).trigger("blur.placeholder").end()};a(function(){a("form").bind("submit.placeholder",function(){var c=a(".placeholder",this).each(b);setTimeout(function(){c.each(f)},10)})});a(window).bind("unload.placeholder",function(){a(".placeholder").val("")})})(jQuery);
jQuery.cookie=function(a,c,b){if(arguments.length>1&&(c===null||typeof c!=="object")){b=jQuery.extend({},b);if(c===null)b.expires=-1;if(typeof b.expires==="number"){var f=b.expires,d=b.expires=new Date;d.setDate(d.getDate()+f)}return document.cookie=[encodeURIComponent(a),"=",b.raw?String(c):encodeURIComponent(String(c)),b.expires?"; expires="+b.expires.toUTCString():"",b.path?"; path="+b.path:"",b.domain?"; domain="+b.domain:"",b.secure?"; secure":""].join("")}b=c||{};d=b.raw?function(a){return a}:
decodeURIComponent;return(f=RegExp("(?:^|; )"+encodeURIComponent(a)+"=([^;]*)").exec(document.cookie))?d(f[1]):null};
